// Sample the baked terrain under Fulton Plaza, in the plaza's own (u, v) frame.
//
//     node sample_terrain.mjs          # writes data/terrain_uv.json
//
// Why this exists. `placeGeneric()` in app/src/assets.js seats a landmark from
// ONE terrain sample, at the anchor:
//
//     const y = Math.max(0, data.sampleElevation(x, z));
//
// Right for a building, wrong for an asset that IS the ground. Fulton falls
// 2.2 m across this block — 18.9 m at Larkin, 16.7 m at Hyde — so a flat slab
// seated at the anchor's 17.79 m would bury the west end by ~0.9 m and float
// the east end by ~1.1 m. `64-south-park` paid for this lesson in twelve build
// iterations; read its REFERENCE.md, "The terrain drape".
//
// Unlike South Park, this profile is TWO-dimensional: the cross-fall is small
// but not negligible (the library side stands higher than the museum side at
// the west end), so dy is sampled on a grid rather than reduced to dy(u).
//
// The heightmap read here is app/public/tiles/terrain.bin — the shipped copy of
// the bake output, and the exact array app/src/data.js indexes at runtime. That
// makes this sampler agree with the loader by construction, which matters more
// than agreeing with pipeline/out (which is not committed).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '../..');
const { project } = await import(`${REPO}/pipeline/lib/geo.mjs`);

const manifest = JSON.parse(fs.readFileSync(`${REPO}/app/public/tiles/manifest.json`, 'utf8'));
const t = manifest.terrain;
const buf = fs.readFileSync(`${REPO}/app/public/tiles/terrain.bin`);
const height = new Int16Array(buf.buffer, buf.byteOffset, buf.byteLength / 2);

// Byte-for-byte the runtime's sampler (app/src/data.js).
function sampleElevation(x, z) {
  const fx = (x - t.minX) / t.cellX;
  const fz = (z - t.minZ) / t.cellZ;
  const ix = Math.min(t.size - 2, Math.max(0, Math.floor(fx)));
  const iz = Math.min(t.size - 2, Math.max(0, Math.floor(fz)));
  const tx = Math.min(1, Math.max(0, fx - ix));
  const tz = Math.min(1, Math.max(0, fz - iz));
  const row = iz * t.size + ix;
  const a = height[row], b = height[row + 1];
  const c = height[row + t.size], d = height[row + t.size + 1];
  const top = a + (b - a) * tx;
  const bot = c + (d - c) * tx;
  return (top + (bot - top) * tz) * t.scale;
}

const plaza = JSON.parse(fs.readFileSync(path.join(HERE, 'data', 'plaza_uv.json'), 'utf8'));
const [ax, az] = project(...plaza.anchor_lonlat);
const H = (plaza.heading_long_deg * Math.PI) / 180;
const C = (plaza.heading_cross_deg * Math.PI) / 180;
const U = [Math.sin(H), Math.cos(H)];
const V = [Math.sin(C), Math.cos(C)];
const toWorld = (u, v) => [ax + u * U[0] + v * V[0], az - (u * U[1] + v * V[1])];

const base = sampleElevation(ax, az);

// A little past the kerb on every side: the north planting beds overhang the
// property line by up to 2 m (plan 2.3) and the drape has to reach them.
const U_MIN = -64, U_MAX = 64, U_STEP = 4;
const V_MIN = -28, V_MAX = 28, V_STEP = 4;
const nu = Math.round((U_MAX - U_MIN) / U_STEP) + 1;
const nv = Math.round((V_MAX - V_MIN) / V_STEP) + 1;
const dy = [];
let lo = Infinity, hi = -Infinity;
for (let j = 0; j < nv; j++) {
  const row = [];
  for (let i = 0; i < nu; i++) {
    const d = sampleElevation(...toWorld(U_MIN + i * U_STEP, V_MIN + j * V_STEP)) - base;
    row.push(Math.round(d * 1000) / 1000);
    lo = Math.min(lo, d); hi = Math.max(hi, d);
  }
  dy.push(row);
}

// How much of the fall is along the axis vs across it — the number that decides
// whether a 1-D profile would have done.
let crossMax = 0;
for (let i = 0; i < nu; i++) {
  let mn = Infinity, mx = -Infinity;
  for (let j = 0; j < nv; j++) { mn = Math.min(mn, dy[j][i]); mx = Math.max(mx, dy[j][i]); }
  crossMax = Math.max(crossMax, mx - mn);
}

const out = {
  _: 'GENERATED by sample_terrain.mjs — do not hand-edit',
  source: 'app/public/tiles/terrain.bin via manifest.terrain — the same array app/src/data.js samples at runtime',
  anchor_lonlat: plaza.anchor_lonlat,
  anchor_elevation_m: Math.round(base * 1000) / 1000,
  u_min: U_MIN, u_step: U_STEP, u_count: nu,
  v_min: V_MIN, v_step: V_STEP, v_count: nv,
  dy_min: Math.round(lo * 1000) / 1000,
  dy_max: Math.round(hi * 1000) / 1000,
  fall_m: Math.round((hi - lo) * 1000) / 1000,
  cross_fall_max_m: Math.round(crossMax * 1000) / 1000,
  dy,
};
fs.writeFileSync(path.join(HERE, 'data', 'terrain_uv.json'), JSON.stringify(out, null, 1));

console.log(`anchor elevation    ${out.anchor_elevation_m} m`);
console.log(`dy range            ${out.dy_min} .. ${out.dy_max} m   (fall ${out.fall_m} m)`);
console.log(`worst cross-fall    ${out.cross_fall_max_m} m  <- why dy is a GRID, not a profile`);
console.log(`grid                ${nu} x ${nv} at ${U_STEP} m`);
for (let j = 0; j < nv; j += 3) {
  console.log(`  v=${String(V_MIN + j * V_STEP).padStart(4)}  ` +
    [0, 4, 8, 12, 16, 20, 24, 28, 32].map((i) => dy[j][i].toFixed(2).padStart(6)).join(''));
}
console.log('wrote data/terrain_uv.json');
