// Sample the baked terrain under South Park, in the park's own (u, v) frame.
//
//     node sample_terrain.mjs            # writes data/terrain_uv.json
//
// Why this exists. `placeGeneric()` in app/src/assets.js seats a landmark by
// ONE terrain sample, at the anchor:
//
//     const y = Math.max(0, data.sampleElevation(x, z));
//
// That is right for a building — a compact footprint on a slope buries its base
// on the uphill side, which is what a real building does. It is wrong for this
// asset, because this asset IS the ground: South Park falls 5.85 m over its
// 160 m length (13.58 m at the Second Street end, 7.73 m at Third), and a flat
// slab seated at the anchor's 10.73 m is buried 2.85 m at one end and floating
// 3.00 m at the other. Measured in the running app on 16 Aug 2026: the whole
// north-east half of the park disappeared under the baked landcover, with only
// the tree crowns showing above it.
//
// So the ground geometry is DRAPED on the terrain, and this script is where the
// terrain comes from. The output is a 1-D profile dy(u), because the fall is
// entirely along the long axis — the cross-axis is flat to the metre, which the
// script measures rather than assumes and records in `cross_axis_range_m`.
//
// dy is relative to the anchor's elevation, so dy(0) = 0 by construction: the
// asset's z = 0 plane is the anchor's ground, which is exactly where the loader
// puts it.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '../..');
const { project } = await import(`${REPO}/pipeline/lib/geo.mjs`);
const { loadHeightmap } = await import(`${REPO}/pipeline/lib/heightmap.mjs`);
const { sampleElevation } = await loadHeightmap();

const park = JSON.parse(fs.readFileSync(path.join(HERE, 'data', 'park_uv.json'), 'utf8'));
const [ax, az] = project(...park.anchor_lonlat);
const H = (park.heading_long_deg * Math.PI) / 180;
const C = (park.heading_cross_deg * Math.PI) / 180;
const U = [Math.sin(H), Math.cos(H)];
const V = [Math.sin(C), Math.cos(C)];
// (u, v) -> world (x east, z south). North is -z, hence the sign on the second term.
const toWorld = (u, v) => [ax + u * U[0] + v * V[0], az - (u * U[1] + v * V[1])];

const base = sampleElevation(ax, az);

const STEP = 2.0;
const U_MIN = -86, U_MAX = 86; // a little past the kerb, for the canopy overhang
const profile = [];
for (let u = U_MIN; u <= U_MAX + 1e-9; u += STEP) {
  // average across the park's width so a single noisy DEM cell cannot tilt it
  let sum = 0;
  let n = 0;
  for (let v = -10; v <= 10; v += 5) {
    sum += sampleElevation(...toWorld(u, v));
    n++;
  }
  profile.push(Math.round((sum / n - base) * 1000) / 1000);
}

let crossRange = 0;
for (let u = U_MIN; u <= U_MAX; u += 10) {
  let mn = Infinity;
  let mx = -Infinity;
  for (let v = -11.75; v <= 11.75; v += 2.35) {
    const y = sampleElevation(...toWorld(u, v));
    mn = Math.min(mn, y);
    mx = Math.max(mx, y);
  }
  crossRange = Math.max(crossRange, mx - mn);
}

const out = {
  _: 'GENERATED by sample_terrain.mjs — do not hand-edit',
  source: 'pipeline/lib/heightmap.mjs over pipeline/data/terrarium (AWS Terrarium), the same sampler the bake uses',
  anchor_lonlat: park.anchor_lonlat,
  anchor_elevation_m: Math.round(base * 1000) / 1000,
  u_min: U_MIN,
  u_step: STEP,
  count: profile.length,
  cross_axis_range_m: Math.round(crossRange * 1000) / 1000,
  fall_m: Math.round((Math.max(...profile) - Math.min(...profile)) * 1000) / 1000,
  dy: profile,
};
fs.writeFileSync(path.join(HERE, 'data', 'terrain_uv.json'), JSON.stringify(out, null, 1));

console.log(`anchor elevation      ${out.anchor_elevation_m} m`);
console.log(`fall along the axis   ${out.fall_m} m  (dy ${Math.min(...profile).toFixed(2)} .. ${Math.max(...profile).toFixed(2)})`);
console.log(`cross-axis range      ${out.cross_axis_range_m} m  <- why dy is 1-D`);
console.log(`samples               ${out.count} at ${STEP} m from u=${U_MIN}`);
for (let u = -80; u <= 80; u += 20) {
  const i = Math.round((u - U_MIN) / STEP);
  console.log(`  u=${String(u).padStart(4)}  dy=${profile[i].toFixed(2)}`);
}
console.log('wrote data/terrain_uv.json');
