// The single source of truth for building identity: 26 recipe categories, the
// fixed subcategory list, and every source-value -> subcategory mapping table.
// Both the pipeline and the baked context files speak these ids; the client
// only ever sees the numeric cat and the sub string.

export const CATS = [
  'misc',
  'house',
  'apartments',
  'office',
  'retail',
  'restaurant_cafe',
  'bar',
  'hotel',
  'worship',
  'school',
  'university',
  'hospital',
  'clinic',
  'fire_station',
  'police',
  'library',
  'museum',
  'theater_cinema',
  'government',
  'industrial',
  'warehouse',
  'gas_station',
  'supermarket',
  'parking_garage',
  'gym',
  'transit_station',
];

export const CAT_INDEX = new Map(CATS.map((c, i) => [c, i]));

// Every subcategory maps to exactly one parent category. Unknown source values
// fall back to the parent category id (sub omitted).
export const SUBS = {
  // 1 house
  house: 1,
  victorian: 1,
  // 2 apartments
  apartments: 2,
  senior_housing: 2,
  dormitory: 2,
  // 3 office
  office: 3,
  tech_hq: 3,
  data_center: 3,
  coworking: 3,
  // 4 retail
  shop: 4,
  corner_store: 4,
  bookstore: 4,
  pharmacy: 4,
  hardware_store: 4,
  florist: 4,
  salon: 4,
  laundromat: 4,
  dry_cleaner: 4,
  car_dealer: 4,
  auto_repair: 4,
  pet_store: 4,
  thrift_store: 4,
  dispensary: 4,
  bank: 4,
  // 5 restaurant_cafe
  restaurant: 5,
  cafe: 5,
  bakery: 5,
  taqueria: 5,
  pizzeria: 5,
  ice_cream: 5,
  food_hall: 5,
  // 6 bar
  bar: 6,
  brewery: 6,
  wine_bar: 6,
  nightclub: 6,
  // 7 hotel
  hotel: 7,
  motel: 7,
  hostel: 7,
  inn: 7,
  // 8 worship
  church: 8,
  cathedral: 8,
  synagogue: 8,
  mosque: 8,
  temple: 8,
  meeting_house: 8,
  // 9 school
  elementary_school: 9,
  middle_school: 9,
  high_school: 9,
  preschool: 9,
  // 10 university
  university: 10,
  college: 10,
  trade_school: 10,
  // 11 hospital
  hospital: 11,
  medical_center: 11,
  // 12 clinic
  clinic: 12,
  dental: 12,
  veterinary: 12,
  urgent_care: 12,
  // 13-16 single-sub civics
  fire_station: 13,
  police_station: 14,
  library: 15,
  museum: 16,
  gallery: 16,
  aquarium: 16,
  science_center: 16,
  // 17 theater_cinema
  theater: 17,
  cinema: 17,
  concert_hall: 17,
  comedy_club: 17,
  // 18 government
  city_hall: 18,
  courthouse: 18,
  post_office: 18,
  consulate: 18,
  civic_office: 18,
  // 19 industrial
  factory: 19,
  workshop: 19,
  utility: 19,
  shipyard: 19,
  // 20 warehouse
  warehouse: 20,
  self_storage: 20,
  distribution: 20,
  // 21 gas_station
  gas_station: 21,
  ev_charging: 21,
  // 22 supermarket
  supermarket: 22,
  grocery: 22,
  // 23 parking
  parking_garage: 23,
  // 24 gym
  gym: 24,
  yoga_studio: 24,
  martial_arts: 24,
  pool: 24,
  // 25 transit
  bart_station: 25,
  muni_station: 25,
  ferry_terminal: 25,
  cable_car_barn: 25,
  // 0 misc
  misc: 0,
  community_center: 0,
  event_venue: 0,
  marina: 0,
  radio_tower: 0,
  greenhouse: 0,
};

export function catOf(sub) {
  const c = SUBS[sub];
  return c === undefined ? null : c;
}

// Human labels for the info card; never show a raw snake_case id.
export const LABELS = {
  misc: 'Building',
  house: 'House',
  victorian: 'Victorian house',
  apartments: 'Apartments',
  senior_housing: 'Senior housing',
  dormitory: 'Dormitory',
  office: 'Office',
  tech_hq: 'Tech office',
  data_center: 'Data center',
  coworking: 'Coworking space',
  shop: 'Shop',
  corner_store: 'Corner store',
  bookstore: 'Bookstore',
  pharmacy: 'Pharmacy',
  hardware_store: 'Hardware store',
  florist: 'Florist',
  salon: 'Salon',
  laundromat: 'Laundromat',
  dry_cleaner: 'Dry cleaner',
  car_dealer: 'Car dealership',
  auto_repair: 'Auto repair',
  pet_store: 'Pet store',
  thrift_store: 'Thrift store',
  dispensary: 'Dispensary',
  bank: 'Bank',
  restaurant: 'Restaurant',
  cafe: 'Café',
  bakery: 'Bakery',
  taqueria: 'Taquería',
  pizzeria: 'Pizzeria',
  ice_cream: 'Ice cream shop',
  food_hall: 'Food hall',
  bar: 'Bar',
  brewery: 'Brewery',
  wine_bar: 'Wine bar',
  nightclub: 'Nightclub',
  hotel: 'Hotel',
  motel: 'Motel',
  hostel: 'Hostel',
  inn: 'Inn',
  church: 'Church',
  cathedral: 'Cathedral',
  synagogue: 'Synagogue',
  mosque: 'Mosque',
  temple: 'Temple',
  meeting_house: 'Meeting house',
  elementary_school: 'Elementary school',
  middle_school: 'Middle school',
  high_school: 'High school',
  preschool: 'Preschool',
  university: 'University',
  college: 'College',
  trade_school: 'Trade school',
  hospital: 'Hospital',
  medical_center: 'Medical center',
  clinic: 'Clinic',
  dental: 'Dental office',
  veterinary: 'Veterinary clinic',
  urgent_care: 'Urgent care',
  fire_station: 'Fire station',
  police_station: 'Police station',
  library: 'Library',
  museum: 'Museum',
  gallery: 'Gallery',
  aquarium: 'Aquarium',
  science_center: 'Science center',
  theater: 'Theater',
  cinema: 'Cinema',
  concert_hall: 'Concert hall',
  comedy_club: 'Comedy club',
  city_hall: 'City hall',
  courthouse: 'Courthouse',
  post_office: 'Post office',
  consulate: 'Consulate',
  civic_office: 'Civic office',
  factory: 'Factory',
  workshop: 'Workshop',
  utility: 'Utility building',
  shipyard: 'Shipyard',
  warehouse: 'Warehouse',
  self_storage: 'Self storage',
  distribution: 'Distribution center',
  gas_station: 'Gas station',
  ev_charging: 'EV charging',
  supermarket: 'Supermarket',
  grocery: 'Grocery store',
  parking_garage: 'Parking garage',
  gym: 'Gym',
  yoga_studio: 'Yoga studio',
  martial_arts: 'Martial arts studio',
  pool: 'Swimming pool',
  bart_station: 'BART station',
  muni_station: 'Muni station',
  ferry_terminal: 'Ferry terminal',
  cable_car_barn: 'Cable car barn',
  community_center: 'Community center',
  event_venue: 'Event venue',
  marina: 'Marina',
  radio_tower: 'Radio tower',
  greenhouse: 'Greenhouse',
};

export const CAT_LABELS = [
  'Building',
  'House',
  'Apartments',
  'Office',
  'Retail',
  'Restaurant / Café',
  'Bar',
  'Hotel',
  'Place of worship',
  'School',
  'University',
  'Hospital',
  'Clinic',
  'Fire station',
  'Police station',
  'Library',
  'Museum',
  'Theater / Cinema',
  'Government',
  'Industrial',
  'Warehouse',
  'Gas station',
  'Supermarket',
  'Parking garage',
  'Gym',
  'Transit station',
];

// ---------------------------------------------------------------- OSM tags
// Explicit, per-tag mapping. Anything not listed is reported as an unmapped
// value by lore.mjs rather than being silently guessed.
const OSM_AMENITY = {
  restaurant: 'restaurant',
  fast_food: 'restaurant',
  food_court: 'food_hall',
  cafe: 'cafe',
  ice_cream: 'ice_cream',
  bar: 'bar',
  pub: 'bar',
  biergarten: 'bar',
  nightclub: 'nightclub',
  place_of_worship: 'church',
  monastery: 'church',
  school: 'elementary_school',
  kindergarten: 'preschool',
  childcare: 'preschool',
  college: 'college',
  university: 'university',
  driving_school: 'trade_school',
  language_school: 'trade_school',
  music_school: 'trade_school',
  hospital: 'hospital',
  clinic: 'clinic',
  doctors: 'clinic',
  dentist: 'dental',
  veterinary: 'veterinary',
  pharmacy: 'pharmacy',
  fire_station: 'fire_station',
  police: 'police_station',
  prison: 'civic_office',
  courthouse: 'courthouse',
  townhall: 'city_hall',
  post_office: 'post_office',
  embassy: 'consulate',
  public_building: 'civic_office',
  library: 'library',
  arts_centre: 'theater',
  theatre: 'theater',
  cinema: 'cinema',
  music_venue: 'concert_hall',
  community_centre: 'community_center',
  social_centre: 'community_center',
  social_facility: 'community_center',
  events_venue: 'event_venue',
  conference_centre: 'event_venue',
  fuel: 'gas_station',
  charging_station: 'ev_charging',
  bank: 'bank',
  bureau_de_change: 'bank',
  marketplace: 'grocery',
  parking: 'parking_garage',
  parking_entrance: 'parking_garage',
  car_rental: 'car_dealer',
  car_wash: 'auto_repair',
  bus_station: 'muni_station',
  ferry_terminal: 'ferry_terminal',
  gym: 'gym',
  swimming_pool: 'pool',
  studio: 'office',
  coworking_space: 'coworking',
  nursing_home: 'senior_housing',
};

const OSM_SHOP = {
  supermarket: 'supermarket',
  grocery: 'grocery',
  greengrocer: 'grocery',
  butcher: 'grocery',
  seafood: 'grocery',
  deli: 'grocery',
  convenience: 'corner_store',
  general: 'corner_store',
  kiosk: 'corner_store',
  bakery: 'bakery',
  pastry: 'bakery',
  confectionery: 'bakery',
  chocolate: 'bakery',
  coffee: 'cafe',
  tea: 'cafe',
  books: 'bookstore',
  newsagent: 'bookstore',
  stationery: 'bookstore',
  chemist: 'pharmacy',
  optician: 'pharmacy',
  medical_supply: 'pharmacy',
  hardware: 'hardware_store',
  doityourself: 'hardware_store',
  paint: 'hardware_store',
  trade: 'hardware_store',
  florist: 'florist',
  garden_centre: 'florist',
  hairdresser: 'salon',
  beauty: 'salon',
  nail: 'salon',
  massage: 'salon',
  tattoo: 'salon',
  hairdresser_supply: 'salon',
  cosmetics: 'salon',
  perfumery: 'salon',
  laundry: 'laundromat',
  dry_cleaning: 'dry_cleaner',
  car: 'car_dealer',
  car_parts: 'auto_repair',
  car_repair: 'auto_repair',
  tyres: 'auto_repair',
  motorcycle: 'car_dealer',
  motorcycle_repair: 'auto_repair',
  pet: 'pet_store',
  pet_grooming: 'pet_store',
  charity: 'thrift_store',
  second_hand: 'thrift_store',
  variety_store: 'thrift_store',
  cannabis: 'dispensary',
  alcohol: 'shop',
  wine: 'shop',
  beverages: 'shop',
  clothes: 'shop',
  shoes: 'shop',
  jewelry: 'shop',
  gift: 'shop',
  furniture: 'shop',
  electronics: 'shop',
  mobile_phone: 'shop',
  computer: 'shop',
  hifi: 'shop',
  bicycle: 'shop',
  sports: 'shop',
  outdoor: 'shop',
  toys: 'shop',
  music: 'shop',
  musical_instrument: 'shop',
  art: 'shop',
  antiques: 'shop',
  interior_decoration: 'shop',
  houseware: 'shop',
  kitchen: 'shop',
  bag: 'shop',
  fabric: 'shop',
  craft: 'shop',
  copyshop: 'shop',
  photo: 'shop',
  travel_agency: 'shop',
  tobacco: 'shop',
  'e-cigarette': 'shop',
  department_store: 'shop',
  mall: 'shop',
  hearing_aids: 'shop',
  locksmith: 'shop',
  tailor: 'shop',
  shoe_repair: 'shop',
  watches: 'shop',
  video_games: 'shop',
  games: 'shop',
  frame: 'shop',
  lighting: 'shop',
  appliance: 'shop',
  bed: 'shop',
  carpet: 'shop',
  curtain: 'shop',
  hardware_store: 'hardware_store',
  storage_rental: 'self_storage',
  funeral_directors: 'shop',
  yes: 'shop',
  vacant: 'shop',
};

const OSM_TOURISM = {
  hotel: 'hotel',
  motel: 'motel',
  hostel: 'hostel',
  guest_house: 'inn',
  apartment: 'apartments',
  chalet: 'inn',
  museum: 'museum',
  gallery: 'gallery',
  aquarium: 'aquarium',
  attraction: null,
  artwork: null,
  information: null,
  viewpoint: null,
  picnic_site: null,
};

const OSM_BUILDING = {
  church: 'church',
  cathedral: 'cathedral',
  chapel: 'church',
  synagogue: 'synagogue',
  mosque: 'mosque',
  temple: 'temple',
  religious: 'church',
  school: 'elementary_school',
  kindergarten: 'preschool',
  university: 'university',
  college: 'college',
  dormitory: 'dormitory',
  hospital: 'hospital',
  clinic: 'clinic',
  fire_station: 'fire_station',
  government: 'civic_office',
  civic: 'civic_office',
  public: 'civic_office',
  courthouse: 'courthouse',
  hotel: 'hotel',
  motel: 'motel',
  commercial: 'office',
  office: 'office',
  retail: 'shop',
  supermarket: 'supermarket',
  kiosk: 'corner_store',
  industrial: 'factory',
  manufacture: 'factory',
  factory: 'factory',
  warehouse: 'warehouse',
  storage_tank: 'utility',
  service: 'utility',
  transformer_tower: 'utility',
  parking: 'parking_garage',
  garages: 'parking_garage',
  carport: 'parking_garage',
  train_station: 'muni_station',
  transportation: 'muni_station',
  hangar: 'warehouse',
  stadium: 'event_venue',
  sports_hall: 'gym',
  sports_centre: 'gym',
  greenhouse: 'greenhouse',
  terrace: 'house',
  detached: 'house',
  semidetached_house: 'house',
  bungalow: 'house',
  cabin: 'house',
  static_caravan: 'house',
  dormitory_building: 'dormitory',
  apartment: 'apartments',
  apartment_building: 'apartments',
  residential_tower: 'apartments',
  civic_office: 'civic_office',
};

const OSM_RELIGION_SUB = {
  jewish: 'synagogue',
  muslim: 'mosque',
  buddhist: 'temple',
  taoist: 'temple',
  hindu: 'temple',
  shinto: 'temple',
  sikh: 'temple',
};

const OSM_OFFICE = {
  government: 'civic_office',
  diplomatic: 'consulate',
  coworking: 'coworking',
  it: 'tech_hq',
  research: 'office',
  company: 'office',
  lawyer: 'office',
  estate_agent: 'office',
  insurance: 'office',
  financial: 'office',
  ngo: 'office',
  association: 'office',
  educational_institution: 'office',
  newspaper: 'office',
  architect: 'office',
  telecommunication: 'office',
  accountant: 'office',
  employment_agency: 'office',
  travel_agent: 'office',
  advertising_agency: 'office',
  charity: 'office',
  yes: 'office',
};

// Unmapped OSM values are reported by lore.mjs; the tables above stay explicit.
export function osmSub(tags) {
  if (!tags) return { sub: null, unmapped: null };
  const { amenity, shop, tourism, building, leisure, railway, office, religion, cuisine } = tags;
  if (amenity === 'place_of_worship') {
    const byReligion = OSM_RELIGION_SUB[religion];
    if (byReligion) return { sub: byReligion, unmapped: null };
    const denom = (tags.denomination || '').toLowerCase();
    if (denom === 'quaker') return { sub: 'meeting_house', unmapped: null };
    if ((tags.building || '') === 'cathedral' || /cathedral/i.test(tags.name || '')) {
      return { sub: 'cathedral', unmapped: null };
    }
    return { sub: 'church', unmapped: null };
  }
  if (amenity === 'restaurant' || amenity === 'fast_food') {
    const c = (cuisine || '').toLowerCase();
    if (/mexican|taco|burrito/.test(c)) return { sub: 'taqueria', unmapped: null };
    if (/pizza/.test(c)) return { sub: 'pizzeria', unmapped: null };
    if (/ice_cream/.test(c)) return { sub: 'ice_cream', unmapped: null };
    if (/coffee|cafe/.test(c)) return { sub: 'cafe', unmapped: null };
    return { sub: 'restaurant', unmapped: null };
  }
  if (amenity === 'bar' || amenity === 'pub') {
    const drink = `${tags['drink:wine'] || ''}${tags.microbrewery || ''}`;
    if (tags.microbrewery === 'yes' || /brew/i.test(tags.name || '')) return { sub: 'brewery', unmapped: null };
    if (/wine/i.test(`${tags.name || ''}${drink}`)) return { sub: 'wine_bar', unmapped: null };
    return { sub: 'bar', unmapped: null };
  }
  if (amenity === 'school') {
    const grades = `${tags['isced:level'] || ''} ${tags.name || ''}`.toLowerCase();
    if (/high school|secondary/.test(grades)) return { sub: 'high_school', unmapped: null };
    if (/middle school|junior high/.test(grades)) return { sub: 'middle_school', unmapped: null };
    return { sub: 'elementary_school', unmapped: null };
  }
  if (railway === 'station' || railway === 'subway_entrance') {
    const name = (tags.name || '').toLowerCase();
    if (tags.station === 'subway' || /bart/.test(name)) return { sub: 'bart_station', unmapped: null };
    return { sub: 'muni_station', unmapped: null };
  }
  if (leisure === 'fitness_centre' || leisure === 'sports_centre') return { sub: 'gym', unmapped: null };
  if (leisure === 'swimming_pool') return { sub: 'pool', unmapped: null };
  if (amenity && amenity in OSM_AMENITY) return { sub: OSM_AMENITY[amenity], unmapped: null };
  if (shop && shop in OSM_SHOP) return { sub: OSM_SHOP[shop], unmapped: null };
  if (tourism && tourism in OSM_TOURISM) return { sub: OSM_TOURISM[tourism], unmapped: null };
  if (office && office in OSM_OFFICE) return { sub: OSM_OFFICE[office], unmapped: null };
  if (building && building in OSM_BUILDING) return { sub: OSM_BUILDING[building], unmapped: null };
  const unmapped =
    (amenity && `amenity=${amenity}`) ||
    (shop && `shop=${shop}`) ||
    (tourism && `tourism=${tourism}`) ||
    (office && `office=${office}`) ||
    (building && `building=${building}`) ||
    null;
  return { sub: null, unmapped };
}

// ------------------------------------------------------------ Overture Places
// Overture's primary category ids (which carry the Foursquare OS Places records
// since FSQ retired its public bucket). Explicit rows first, keyword rules for
// the long tail of 1,300+ leaf categories.
const OVERTURE_EXACT = {
  restaurant: 'restaurant',
  fast_food_restaurant: 'restaurant',
  food_truck: 'restaurant',
  diner: 'restaurant',
  cafe: 'cafe',
  coffee_shop: 'cafe',
  tea_room: 'cafe',
  bubble_tea: 'cafe',
  juice_bar_and_smoothies: 'cafe',
  smoothie_juice_bar: 'cafe',
  bakery: 'bakery',
  donuts: 'bakery',
  desserts: 'bakery',
  chocolatier: 'bakery',
  candy_store: 'bakery',
  bagel_shop: 'bakery',
  ice_cream_shop: 'ice_cream',
  taco_restaurant: 'taqueria',
  mexican_restaurant: 'taqueria',
  salvadoran_restaurant: 'taqueria',
  pizza_restaurant: 'pizzeria',
  food_hall: 'food_hall',
  farmers_market: 'grocery',
  bar: 'bar',
  sports_bar: 'bar',
  gay_bar: 'bar',
  bar_and_grill_restaurant: 'bar',
  gastropub: 'bar',
  pub: 'bar',
  lounge: 'bar',
  cocktail_bar: 'bar',
  dive_bar: 'bar',
  beer_bar: 'bar',
  brewery: 'brewery',
  brewpub: 'brewery',
  distillery: 'brewery',
  winery: 'wine_bar',
  wine_bar: 'wine_bar',
  dance_club: 'nightclub',
  nightclub: 'nightclub',
  nightlife: 'nightclub',
  adult_entertainment: 'nightclub',
  hotel: 'hotel',
  accommodation: 'hotel',
  resort: 'hotel',
  motel: 'motel',
  hostel: 'hostel',
  bed_and_breakfast: 'inn',
  church_cathedral: 'church',
  catholic_church: 'church',
  baptist_church: 'church',
  religious_organization: 'church',
  synagogue: 'synagogue',
  mosque: 'mosque',
  buddhist_temple: 'temple',
  hindu_temple: 'temple',
  elementary_school: 'elementary_school',
  private_school: 'elementary_school',
  school: 'elementary_school',
  middle_school: 'middle_school',
  high_school: 'high_school',
  preschool: 'preschool',
  day_care_preschool: 'preschool',
  child_care_and_day_care: 'preschool',
  college_university: 'university',
  campus_building: 'university',
  vocational_and_technical_school: 'trade_school',
  specialty_school: 'trade_school',
  art_school: 'trade_school',
  language_school: 'trade_school',
  music_school: 'trade_school',
  cooking_school: 'trade_school',
  dance_school: 'trade_school',
  tutoring_center: 'trade_school',
  hospital: 'hospital',
  medical_center: 'medical_center',
  emergency_room: 'hospital',
  urgent_care_clinic: 'urgent_care',
  doctor: 'clinic',
  dentist: 'dental',
  general_dentistry: 'dental',
  cosmetic_dentist: 'dental',
  orthodontist: 'dental',
  oral_surgeon: 'dental',
  veterinarian: 'veterinary',
  fire_department: 'fire_station',
  police_department: 'police_station',
  library: 'library',
  museum: 'museum',
  art_museum: 'museum',
  history_museum: 'museum',
  aquarium: 'aquarium',
  science_museum: 'science_center',
  art_gallery: 'gallery',
  theatre: 'theater',
  performing_arts: 'theater',
  theatrical_productions: 'theater',
  cinema: 'cinema',
  movie_theater: 'cinema',
  comedy_club: 'comedy_club',
  music_venue: 'concert_hall',
  topic_concert_venue: 'concert_hall',
  city_hall: 'city_hall',
  courthouse: 'courthouse',
  post_office: 'post_office',
  embassy: 'consulate',
  federal_government_offices: 'civic_office',
  public_service_and_government: 'civic_office',
  public_and_government_association: 'civic_office',
  gas_station: 'gas_station',
  ev_charging_station: 'ev_charging',
  supermarket: 'supermarket',
  grocery_store: 'grocery',
  specialty_grocery_store: 'grocery',
  asian_grocery_store: 'grocery',
  health_food_store: 'grocery',
  convenience_store: 'corner_store',
  liquor_store: 'shop',
  parking: 'parking_garage',
  gym: 'gym',
  fitness_trainer: 'gym',
  yoga_studio: 'yoga_studio',
  pilates_studio: 'yoga_studio',
  martial_arts_club: 'martial_arts',
  train_station: 'bart_station',
  bus_station: 'muni_station',
  transportation: 'muni_station',
  bookstore: 'bookstore',
  pharmacy: 'pharmacy',
  hardware_store: 'hardware_store',
  home_improvement_store: 'hardware_store',
  building_supply_store: 'hardware_store',
  florist: 'florist',
  flowers_and_gifts_shop: 'florist',
  hair_salon: 'salon',
  beauty_salon: 'salon',
  nail_salon: 'salon',
  barber: 'salon',
  spas: 'salon',
  day_spa: 'salon',
  massage: 'salon',
  waxing: 'salon',
  skin_care: 'salon',
  tattoo_and_piercing: 'salon',
  laundromat: 'laundromat',
  laundry_services: 'laundromat',
  dry_cleaning: 'dry_cleaner',
  car_dealer: 'car_dealer',
  motorcycle_dealer: 'car_dealer',
  car_rental_agency: 'car_dealer',
  automotive_repair: 'auto_repair',
  auto_body_shop: 'auto_repair',
  car_wash: 'auto_repair',
  auto_glass_service: 'auto_repair',
  pet_store: 'pet_store',
  pet_groomer: 'pet_store',
  thrift_store: 'thrift_store',
  used_vintage_and_consignment: 'thrift_store',
  antique_store: 'thrift_store',
  cannabis_dispensary: 'dispensary',
  bank_credit_union: 'bank',
  banks: 'bank',
  credit_union: 'bank',
  coworking_space: 'coworking',
  software_development: 'tech_hq',
  information_technology_company: 'tech_hq',
  biotechnology_company: 'tech_hq',
  corporate_office: 'office',
  professional_services: 'office',
  apartments: 'apartments',
  condominium: 'apartments',
  retirement_home: 'senior_housing',
  self_storage_facility: 'self_storage',
  storage_facility: 'self_storage',
  warehouse: 'warehouse',
  freight_and_cargo_service: 'distribution',
  courier_and_delivery_services: 'distribution',
  shipping_center: 'distribution',
  industrial_equipment: 'factory',
  manufacturing: 'factory',
  community_center: 'community_center',
  cultural_center: 'community_center',
  community_services_non_profits: 'community_center',
  venue_and_event_space: 'event_venue',
  stadium_arena: 'event_venue',
  marina: 'marina',
  radio_station: 'radio_tower',
  landmark_and_historical_building: null,
  park: null,
  playground: null,
  beach: null,
  monument: null,
  sculpture_statue: null,
  dog_park: null,
  hiking_trail: null,
  public_plaza: null,
  bridge: null,
  tennis_court: null,
  baseball_field: null,
  atms: null,
  organization: null,
  business: null,
  shopping: 'shop',
  retail: 'shop',
  eat_and_drink: 'restaurant',
  food: 'restaurant',
  health_and_medical: 'clinic',
  education: 'elementary_school',
  active_life: 'gym',
  arts_and_entertainment: 'theater',
  sports_and_recreation_venue: 'gym',
  attractions_and_activities: null,
  travel: null,
  automotive: 'auto_repair',
  beauty_and_spa: 'salon',
  home_service: null,
  real_estate: 'office',
};

const OVERTURE_RULES = [
  [/_restaurant$|^restaurant_|steakhouse|noodles|barbecue|sandwich_shop|salad_bar|deli(catessen)?$/, 'restaurant'],
  [/coffee|cafe|tea_/, 'cafe'],
  [/bakery|pastry/, 'bakery'],
  [/_bar$|^bar_|pub$|tavern/, 'bar'],
  [/hotel|motel|hostel|lodging/, 'hotel'],
  [/church|chapel|temple|mosque|synagogue|worship/, 'church'],
  [/school$/, 'elementary_school'],
  [/university|college/, 'university'],
  [/hospital/, 'hospital'],
  [/dentist|dental|orthodont/, 'dental'],
  [
    /doctor|physician|clinic|medical|surgeon|pediatric|dermatolog|cardiolog|oncolog|neurolog|psychiatr|psycholog|therapy|therapist|chiropract|acupunctur|podiatr|optometrist|obstetric|gastroenterolog|orthoped|counseling|nurse/,
    'clinic',
  ],
  [/veterinar|animal_hospital/, 'veterinary'],
  [/museum/, 'museum'],
  [/gallery/, 'gallery'],
  [/theater|theatre/, 'theater'],
  [/cinema|movie/, 'cinema'],
  [/library/, 'library'],
  [/government|municipal|civic/, 'civic_office'],
  [/gas_station|fuel/, 'gas_station'],
  [/grocer|supermarket/, 'grocery'],
  [/parking/, 'parking_garage'],
  [/gym|fitness|crossfit/, 'gym'],
  [/yoga/, 'yoga_studio'],
  [/salon|barber|nail|spa$|beauty/, 'salon'],
  [/laundr/, 'laundromat'],
  [/pharmac|drugstore/, 'pharmacy'],
  [/book(store|shop)/, 'bookstore'],
  [/florist|flower/, 'florist'],
  [/auto|car_repair|tire|towing/, 'auto_repair'],
  [/pet_/, 'pet_store'],
  [/storage/, 'self_storage'],
  [/warehouse|wholesale/, 'warehouse'],
  [/factory|manufactur|industrial/, 'factory'],
  [/_store$|_shop$|boutique|market$/, 'shop'],
  [
    /lawyer|law$|legal|accountant|insurance|advertis|marketing|consult|agency|agent|architect|engineer|designer|_company$|_services$|_service$|office/,
    'office',
  ],
];

export function overtureSub(category) {
  if (!category) return { sub: null, unmapped: null };
  if (category in OVERTURE_EXACT) return { sub: OVERTURE_EXACT[category], unmapped: null };
  for (const [re, sub] of OVERTURE_RULES) if (re.test(category)) return { sub, unmapped: null };
  return { sub: null, unmapped: category };
}

// -------------------------------------------------------------------- NAICS
// DataSF Registered Business Locations self-reported codes. Longest prefix wins.
const NAICS = [
  ['7211', 'hotel'],
  ['72111', 'hotel'],
  ['72112', 'motel'],
  ['7212', 'hotel'],
  ['7213', 'hostel'],
  ['7223', 'restaurant'],
  ['722511', 'restaurant'],
  ['722513', 'restaurant'],
  ['722514', 'cafe'],
  ['722515', 'cafe'],
  ['7225', 'restaurant'],
  ['72233', 'restaurant'],
  ['7224', 'bar'],
  ['722410', 'bar'],
  ['312120', 'brewery'],
  ['3121', 'brewery'],
  ['722', 'restaurant'],
  ['4451', 'supermarket'],
  ['445110', 'supermarket'],
  ['445120', 'corner_store'],
  ['4452', 'grocery'],
  ['445', 'grocery'],
  ['4453', 'shop'],
  ['446110', 'pharmacy'],
  ['4461', 'pharmacy'],
  ['447', 'gas_station'],
  ['4471', 'gas_station'],
  ['457', 'gas_station'],
  ['4411', 'car_dealer'],
  ['4412', 'car_dealer'],
  ['441', 'car_dealer'],
  ['8111', 'auto_repair'],
  ['4413', 'auto_repair'],
  ['4442', 'hardware_store'],
  ['4441', 'hardware_store'],
  ['444', 'hardware_store'],
  ['45311', 'florist'],
  ['4531', 'florist'],
  ['45391', 'pet_store'],
  ['4539', 'shop'],
  ['459', 'shop'],
  ['45121', 'bookstore'],
  ['4512', 'bookstore'],
  ['45331', 'thrift_store'],
  ['8123', 'laundromat'],
  ['812310', 'laundromat'],
  ['812320', 'dry_cleaner'],
  ['8121', 'salon'],
  ['812112', 'salon'],
  ['812113', 'salon'],
  ['812199', 'salon'],
  ['81293', 'parking_garage'],
  ['812930', 'parking_garage'],
  ['44', 'shop'],
  ['45', 'shop'],
  ['5311', 'apartments'],
  ['531110', 'apartments'],
  ['62321', 'senior_housing'],
  ['6233', 'senior_housing'],
  ['6111', 'elementary_school'],
  ['611110', 'elementary_school'],
  ['611310', 'university'],
  ['6113', 'university'],
  ['6112', 'college'],
  ['6115', 'trade_school'],
  ['6116', 'trade_school'],
  ['6244', 'preschool'],
  ['624410', 'preschool'],
  ['622', 'hospital'],
  ['6221', 'hospital'],
  ['6214', 'clinic'],
  ['6211', 'clinic'],
  ['621210', 'dental'],
  ['6212', 'dental'],
  ['54194', 'veterinary'],
  ['621', 'clinic'],
  ['71394', 'gym'],
  ['713940', 'gym'],
  ['7139', 'gym'],
  ['71311', 'event_venue'],
  ['7121', 'museum'],
  ['712110', 'museum'],
  ['712130', 'aquarium'],
  ['7111', 'theater'],
  ['512131', 'cinema'],
  ['51213', 'cinema'],
  ['8131', 'church'],
  ['813110', 'church'],
  ['4931', 'self_storage'],
  ['493', 'warehouse'],
  ['4841', 'distribution'],
  ['4921', 'distribution'],
  ['492', 'distribution'],
  ['485', 'muni_station'],
  ['31', 'factory'],
  ['32', 'factory'],
  ['33', 'factory'],
  ['22', 'utility'],
  ['5182', 'data_center'],
  ['5415', 'tech_hq'],
  ['5112', 'tech_hq'],
  ['5417', 'office'],
  ['54', 'office'],
  ['55', 'office'],
  ['56', 'office'],
  ['52211', 'bank'],
  ['5221', 'bank'],
  ['522', 'bank'],
  ['51', 'office'],
  ['53', 'office'],
  ['92', 'civic_office'],
  ['81311', 'church'],
  ['813', 'community_center'],
].sort((a, b) => b[0].length - a[0].length);

export function naicsSub(code) {
  if (!code) return { sub: null, unmapped: null };
  const digits = String(code).replace(/\D/g, '');
  if (!digits) return { sub: null, unmapped: null };
  for (const [prefix, sub] of NAICS) if (digits.startsWith(prefix)) return { sub, unmapped: null };
  return { sub: null, unmapped: `naics=${digits.slice(0, 4)}` };
}

// ------------------------------------------------ DataSF facilities & schools
// City Facilities carries a department and a common name rather than a type
// code, so the mapping is keyword-based over both, most specific first.
const FACILITY_RULES = [
  [/fire (station|house)|engine co|firehouse/i, 'fire_station'],
  [/police (station|district)|hall of justice/i, 'police_station'],
  [/branch library|library/i, 'library'],
  [/city hall/i, 'city_hall'],
  [/court(house)?/i, 'courthouse'],
  [/hospital|general campus|laguna honda/i, 'hospital'],
  [/health center|clinic|urgent care/i, 'clinic'],
  [/\bmuseum\b|de young|legion of honor|academy of sciences/i, 'museum'],
  [/theat(er|re)|auditorium|opera house|symphony/i, 'theater'],
  [/rec(reation)? center|clubhouse|community center/i, 'community_center'],
  [/swimming pool|natatorium/i, 'pool'],
  [/\bgym(nasium)?\b/i, 'gym'],
  [/school|academy|elementary|middle school|high school/i, 'elementary_school'],
  [/college|university/i, 'college'],
  [/\bpier\b|ferry/i, 'ferry_terminal'],
  [/parking garage|garage/i, 'parking_garage'],
  [/\bpump station\b|reservoir|substation|water treatment|valve house|utility|power/i, 'utility'],
  [/yard|shop|maintenance|corporation yard|machine shop/i, 'workshop'],
  [/warehouse|storage/i, 'warehouse'],
  [/office|administration|annex|bureau|hall\b/i, 'civic_office'],
];

const FACILITY_DEPT = {
  'Fire Department': 'fire_station',
  'Police Department': 'police_station',
  'Public Library': 'library',
  'Recreation and Park Commission': 'community_center',
  'Recreation And Parks': 'community_center',
  'Recreation and Parks': 'community_center',
  'Department of Public Health': 'clinic',
  'Municipal Transportation Agency': 'muni_station',
  'Public Utilities Commission': 'utility',
  'Port': 'utility',
  'Airport Commission': 'utility',
  'Arts Commission': 'museum',
  'Asian Art Museum': 'museum',
  'Fine Arts Museum': 'museum',
  'War Memorial': 'theater',
  'City Administrator': 'civic_office',
  'General Services Agency': 'civic_office',
  'Board of Supervisors': 'city_hall',
  'Superior Court': 'courthouse',
};

export function facilitySub(record) {
  const name = String(record.common_name || '');
  for (const [re, sub] of FACILITY_RULES) if (re.test(name)) return { sub, unmapped: null };
  const dept = FACILITY_DEPT[record.department_name];
  if (dept) return { sub: dept, unmapped: null };
  return { sub: 'civic_office', unmapped: record.department_name || null };
}

export function schoolSub(record) {
  const low = parseInt(record.low_grade, 10);
  const high = parseInt(record.high_grade, 10);
  const type = `${record.entity_type || ''} ${record.educational_program_type || ''}`.toLowerCase();
  if (/preschool|early education|child development/.test(type)) return 'preschool';
  if (Number.isFinite(high) && high >= 9) return 'high_school';
  if (Number.isFinite(low) && low >= 6) return 'middle_school';
  if (Number.isFinite(high) && high >= 6) return 'middle_school';
  return 'elementary_school';
}

// ------------------------------------------------------------------ Land use
// c5ge-t6pj carries per-parcel square footage by use plus a residential flag;
// the dominant non-residential use wins when there are no dwellings.
export function landuseCat(parcel) {
  const n = (v) => {
    const x = parseFloat(v);
    return Number.isFinite(x) ? x : 0;
  };
  const res = n(parcel.resunits);
  const uses = [
    ['retail', n(parcel.retail), 4],
    ['cie', n(parcel.cie), 0],
    ['med', n(parcel.med), 12],
    ['mips', n(parcel.mips), 3],
    ['pdr', n(parcel.pdr), 19],
    ['visitor', n(parcel.visitor), 7],
  ];
  uses.sort((a, b) => b[1] - a[1]);
  const top = uses[0];
  const commercial = top[1] > 0 ? top[2] : null;
  if (parcel.garage === true || parcel.parking_lo === true) return 23;
  if (res >= 1) {
    // SF's corridors are flats over storefronts: a parcel with real commercial
    // floor area reads as its ground-floor use, which is what the street sees.
    if (commercial !== null && top[1] >= 1000) return commercial;
    return res >= 5 ? 2 : 1;
  }
  return commercial;
}

// Night-window profiles per category (§2.5.1): 0 residential, 1 commercial,
// 2 always-on, 3 dark.
export const NIGHT_PROFILE = (() => {
  const p = new Array(CATS.length).fill(3);
  for (const c of ['house', 'apartments', 'hotel']) p[CAT_INDEX.get(c)] = 0;
  for (const c of [
    'retail',
    'restaurant_cafe',
    'bar',
    'theater_cinema',
    'gym',
    'supermarket',
    'gas_station',
    'museum',
    'library',
  ]) {
    p[CAT_INDEX.get(c)] = 1;
  }
  for (const c of ['hospital', 'clinic', 'fire_station', 'police', 'transit_station', 'government']) {
    p[CAT_INDEX.get(c)] = 2;
  }
  return p;
})();

// Categories whose facades read as punched masonry rather than glass bands.
export const SUPPRESS_BANDS = new Set(
  ['worship', 'industrial', 'warehouse', 'government', 'parking_garage'].map((c) => CAT_INDEX.get(c))
);
