// Reproject the 424 Brannan parcel into the site's own (u, v) frame.
//
//     node extract_site.mjs            # writes data/site_uv.json
//
// Input is data/parcel_3776455.json, the verbatim DataSF Parcels response for
// blklot 3776455 (https://data.sfgov.org/resource/acdm-wktn.json?blklot=3776455),
// committed so this script is deterministic and offline.
//
// The frame. SoMa's grid runs 45.2 deg, so the lot sits at 45 deg to the world
// axes and its axis-aligned bounding box (88.7 x 59.6 m) says nothing useful
// about a site that is 68.4 m along Ritch. Everything is therefore authored in
//   u = along Brannan Street, POSITIVE TOWARD THE NORTH-EAST (bearing 45.2)
//   v = across it, POSITIVE TOWARD BRANNAN ITSELF (bearing 135.2)
// with the origin at the anchor, which is the parcel's axis-aligned bounding-box
// centre — that is what the manifest anchor means to placeGeneric().
//
// The projection constants come from app/public/tiles/manifest.json rather than
// from AGENTS.md's rounded formula: the bake's mPerDegLon is 87995.768, and the
// 0.04% difference against 111320*cos(lat0) is 1.4 m at this distance from the
// origin, which is more than the anchor tolerance.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '../..');
const M = JSON.parse(fs.readFileSync(path.join(REPO, 'app/public/tiles/manifest.json'), 'utf8'));
const { lon0, lat0, mPerDegLon, mPerDegLat } = M.projection;
const project = (lon, lat) => [(lon - lon0) * mPerDegLon, -(lat - lat0) * mPerDegLat];

const HEADING_U = 45.2;   // +u bears 45.2 (north-east, along Brannan)
const HEADING_V = 135.2;  // +v bears 135.2 (south-east, toward Brannan)

const parcel = JSON.parse(fs.readFileSync(path.join(HERE, 'data', 'parcel_3776455.json'), 'utf8'))[0];
const lonlat = parcel.shape.coordinates[0][0];
const world = lonlat.map(([lon, lat]) => project(lon, lat));
// DataSF closes the ring; drop the duplicate last vertex.
if (Math.hypot(world[0][0] - world.at(-1)[0], world[0][1] - world.at(-1)[1]) < 1e-6) world.pop();

const xs = world.map((p) => p[0]);
const zs = world.map((p) => p[1]);
const ax = (Math.min(...xs) + Math.max(...xs)) / 2;
const az = (Math.min(...zs) + Math.max(...zs)) / 2;

const R = (d) => (d * Math.PI) / 180;
const U = [Math.sin(R(HEADING_U)), Math.cos(R(HEADING_U))];  // (east, north)
const V = [Math.sin(R(HEADING_V)), Math.cos(R(HEADING_V))];

// world (x east, z south) -> blender (X east, Y north) -> (u, v)
const toUV = ([x, z]) => {
  const X = x - ax;
  const Y = az - z;
  return [X * U[0] + Y * U[1], X * V[0] + Y * V[1]];
};

const ring = world.map(toUV).map((p) => [round(p[0]), round(p[1])]);
function round(n) { return Math.round(n * 1000) / 1000; }

// shoelace in (u, v)
let area = 0;
for (let i = 0; i < ring.length; i++) {
  const [u0, v0] = ring[i];
  const [u1, v1] = ring[(i + 1) % ring.length];
  area += u0 * v1 - u1 * v0;
}
area = Math.abs(area) / 2;

const edges = ring.map((p, i) => {
  const q = ring[(i + 1) % ring.length];
  const du = q[0] - p[0];
  const dv = q[1] - p[1];
  // outward normal bearing: the ring is CCW in (u, v) or CW; resolve by area sign
  return { i, len: round(Math.hypot(du, dv)) };
});

const out = {
  _: 'GENERATED by extract_site.mjs — do not hand-edit',
  source: 'DataSF Parcels acdm-wktn, blklot 3776455 (data/parcel_3776455.json)',
  projection: { lon0, lat0, mPerDegLon, mPerDegLat },
  anchor_world: [round(ax), round(az)],
  anchor_lonlat: [Math.round((ax / mPerDegLon + lon0) * 1e7) / 1e7,
                  Math.round((-az / mPerDegLat + lat0) * 1e7) / 1e7],
  heading_u_deg: HEADING_U,
  heading_v_deg: HEADING_V,
  area_m2: Math.round(area * 10) / 10,
  bbox_world: [round(Math.max(...xs) - Math.min(...xs)), round(Math.max(...zs) - Math.min(...zs))],
  ring_uv: ring,
  edge_lengths_m: edges.map((e) => e.len),
  // Everything standing on the lot, measured off z21 Google satellite nadir
  // imagery with the parcel ring overlaid (REFERENCE.md s.1). Positions are the
  // feature centres in (u, v).
  features: {
    booth: [14.88, -12.4],
    trailer: [10.96, -15.23],
    thicket: [-2.0, -30.82],
    corner_shrub: [3.76, 43.18],
  },
};
fs.writeFileSync(path.join(HERE, 'data', 'site_uv.json'), JSON.stringify(out, null, 1));

console.log(`anchor        ${out.anchor_lonlat.join(', ')}`);
console.log(`area          ${out.area_m2} m2`);
console.log(`bbox (world)  ${out.bbox_world[0]} x ${out.bbox_world[1]} m`);
console.log(`ring          ${ring.length} vertices`);
ring.forEach((p, i) => console.log(`  V${String(i).padStart(2)}  u=${p[0].toFixed(2).padStart(7)}  v=${p[1].toFixed(2).padStart(7)}   edge ${out.edge_lengths_m[i].toFixed(2)} m`));
console.log('wrote data/site_uv.json');
